### ISSUE TITLE
Merging with the main repo?

### ISSUE THREAD

**Issue by TheTechRobo** [knarkzel/ogc-rs#1]
Out of curiosity, why are you maintaining your own fork?

**Comment by lambdachad** [comment]
I like my own implementation of `pad.rs` better. To me it's more ergonomic.

**Comment by lambdachad** [comment]
See [my implementation](https://github.com/knarkzel/ogc-rs/blob/master/examples/pad.rs#L31-L95) vs [official implementation](https://github.com/rust-wii/ogc-rs/blob/master/examples/embedded-graphics-wii/src/main.rs#L52-L58).

**Comment by lambdachad** [comment]
My implementation is also less prone to ownership issues since getting input doesn't require struct with methods, just pure functions.

**Comment by TheTechRobo** [comment]
I think you sent the wrong link...?

**Comment by lambdachad** [comment]
What do you mean?

**Comment by TheTechRobo** [comment]
Nevermind - I misread the link you send for this repo, I thought it was the source code and not an example and got confused when you sent an example for the original repo.
